Publish preparations
This should trigger a build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,27 +1,17 @@
 language: cpp
-dist: trusty # Note that a trusty instance is limited to 2 cores, max. 4 gb of memory and 20 gb of hard disk space.
-compiler: clang-5.0
-addons:
-  apt:
-    sources:
-    - llvm-toolchain-trusty
-    packages:
-    - clang-5.0
-    - lld-5.0
+dist: trusty # Note that trusty instances are limited to 2 cores, max. 4 gb of memory and 20 gb of hard disk space.
+compiler: clang
 git:
   submodules: false
 cache:
   ccache: true
   directories:
   - $HOME/.emscripten_cache
-notifications:
-  email:
-    on_failure: change
 env:
   global:
   - MAKEFLAGS="-j2"
-  - CFLAGS="-Qunused-arguments -fcolor-diagnostics -fuse-ld=lld-5.0 -O0"
-  - CXXFLAGS="-Qunused-arguments -fcolor-diagnostics -fuse-ld=lld-5.0 -O0"
+  - CFLAGS="-Qunused-arguments -fcolor-diagnostics -fuse-ld=gold"
+  - CXXFLAGS="-Qunused-arguments -fcolor-diagnostics -fuse-ld=gold"
   - CCACHE_SLOPPINESS="pch_defines,time_macros"
   - CCACHE_COMPRESS=1
   - CCACHE_HARDLINK=1
@@ -30,54 +20,86 @@ env:
   - EMSCRIPTEN="$EMSDK/emscripten/incoming"
   - PATH="$HOME/cmake-3.8.2-Linux-x86_64/bin:$EMSDK:$PATH"
 
-install: # install a recent cmake, emsdk-portable and node.js
+install: # install cmake, emsdk-portable and node.js
 - wget --no-check-certificate -qO- https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz | tar -xzC $HOME &&
   wget --no-check-certificate -qO- https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz | tar -xzC $HOME &&
   nvm install 8
 
-before_script: # setup emscripten
-- ccache -z -M ${CCACHE_MAXSIZE} &&
+before_script: # setup ccache, git and emscripten
+- ccache -z -M $CCACHE_MAXSIZE &&
   ccache -s
-- export CC="ccache clang-5.0" &&
-  export CXX="ccache clang++-5.0" &&
-  export LD="ld.lld-5.0" &&
-  export RC=1
-- timeout 40m emsdk install -j2 --build=Release --disable-assertions clang-incoming-64bit &&
-  emsdk install -j2 emscripten-incoming-64bit &&
-  emsdk activate --build=Release clang-incoming-64bit &&
-  emsdk activate emscripten-incoming-64bit &&
-  if [ -f "$HOME/.emscripten_cache/config" ]; then
-    cp $HOME/.emscripten_cache/config $HOME/.emscripten;
-  fi &&
-  git checkout master &&
-  git submodule update --init --remote --merge;
-  export RC=$?;
-  $(exit 0)
-
-script: # build binaryen.js
-- if [ $RC -eq 0 ]; then
-    source $EMSDK/emsdk_env.sh &&
-    cd ./binaryen &&
-    ./build-js.sh &&
-    cp ./bin/binaryen.js ../index.js &&
-    cd .. &&
-    npm install &&
-    npm test
-  else
-    $(exit $RC);
-  fi
-
-before_cache:
-- cp $HOME/.emscripten $HOME/.emscripten_cache/config
-- ccache -s
-
-after_success: # push to github
-# export BINARYEN_LATEST=`tail -n 1 $EMSDK/binaryen-tags.txt`
 - git config --global user.email "travis@travis-ci.org" &&
   git config --global user.name "Travis CI" &&
   git config credential.helper "store --file=.git/credentials" &&
   echo "https://${GH_TOKEN}:@github.com" > .git/credentials &&
+  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc
+- export CC="ccache clang" &&
+  export CXX="ccache clang++" &&
+  export LD="ld.gold" &&
+  export RC=1
+- emsdk update-tags &&
+  timeout 30m
+  emsdk install -j2 --build=Release --disable-assertions clang-incoming-64bit &&
+  emsdk install -j2 emscripten-incoming-64bit &&
+  emsdk activate --build=Release clang-incoming-64bit &&
+  emsdk activate emscripten-incoming-64bit &&
+  git checkout master &&
+  git submodule update --init --remote --merge;
+  export RC=$?
+- $(exit 0)
+
+script: # build binaryen.js
+- if [ $RC -ne 0 ]; then
+    exit $RC;
+  fi;
+  source $EMSDK/emsdk_env.sh &&
+  cd ./binaryen &&
+  ./build-js.sh &&
+  cp ./bin/binaryen.js ../index.js &&
+  cd .. &&
+  npm install &&
+  npm test;
+
+before_cache: # print ccache statistics
+- ccache -s
+
+# --- everything below happens after the cache has been updated ---
+
+after_failure: # trigger continuation if (and only if) the build timed out
+- if [ $RC -eq 124 ]; then
+    git checkout master &&
+    git commit --allow-empty -m "Build continuation notification" &&
+    git push -u origin master;
+  fi
+- exit $RC
+
+after_success: # push to github and publish on npm (intentionally fails for duplicates)
+- RELEASE_VERSION=`tail -n 1 $EMSDK/binaryen-tags.txt` &&
+  NIGHTLY_VERSION=$RELEASE_VERSION"-nightly."`date -u +"%Y%m%d"` &&
   git add ./binaryen &&
   git add ./index.js &&
-  git commit -m "Build ""#""${TRAVIS_BUILD_NUMBER} [ci skip]" &&
-  git push -u origin master
+  if
+    npm version $RELEASE_VERSION --no-git-tag-version --force;
+  then
+    VERSION=$RELEASE_VERSION &&
+    IS_NIGHTLY=0 &&
+    git add ./package.json &&
+    git add ./package-lock.json &&
+    echo "Committing release ("$VERSION") ...";
+  else
+    npm version $NIGHTLY_VERSION --no-git-tag-version --force &&
+    VERSION=$NIGHTLY_VERSION &&
+    IS_NIGHTLY=1 &&
+    echo "Committing nightly ("$VERSION") ...";
+  fi &&
+  git commit -m "Build ""#"$TRAVIS_BUILD_NUMBER" (v"$VERSION") [ci skip]" &&
+  git push -u origin master &&
+  git tag "v"$VERSION &&
+  git push -u origin "v"$VERSION &&
+  if [ $IS_NIGHTLY -eq 1 ]; then
+    echo "Publishing nightly ..." &&
+    npm publish --tag nightly;
+  else
+    echo "Publishing release ..." &&
+    npm publish;
+  fi
